export const ingredients = [
  { id: 1, name: "Сыр моцарелла", price: 50 },
  { id: 2, name: "Острый соус", price: 30 },
  { id: 3, name: "Оливки", price: 40 },
  { id: 4, name: "Доп. пепперони", price: 70 },
  { id: 5, name: "Базилик", price: 20 },
  { id: 6, name: "Помидоры черри", price: 40 },
  { id: 7, name: "Доп. сыр", price: 50 },
  { id: 8, name: "Песто", price: 30 },
  { id: 9, name: "Горгонзола", price: 60 },
  { id: 10, name: "Чеддер", price: 50 },
  { id: 11, name: "Сливочный соус", price: 30 },
  { id: 12, name: "Грибы", price: 40 },
  { id: 13, name: "Доп. ананас", price: 30 },
  { id: 14, name: "Ветчина", price: 50 },
  { id: 15, name: "Курица", price: 50 },
  { id: 16, name: "Бекон", price: 50 },
  { id: 17, name: "Лук", price: 20 },
  { id: 18, name: "Соус барбекю", price: 30 },
  { id: 19, name: "Баклажаны", price: 40 },
  { id: 20, name: "Цукини", price: 40 },
  { id: 21, name: "Перец болгарский", price: 30 },
  { id: 22, name: "Брокколи", price: 30 },
  { id: 23, name: "Салями", price: 50 },
  { id: 24, name: "Говядина", price: 70 },
  { id: 25, name: "Халапеньо", price: 30 },
  { id: 26, name: "Лук красный", price: 20 },
  { id: 27, name: "Белые грибы", price: 50 },
  { id: 28, name: "Трюфельное масло", price: 60 },
  { id: 29, name: "Шампиньоны", price: 40 },
  { id: 30, name: "Креветки", price: 80 },
  { id: 31, name: "Кальмары", price: 70 },
  { id: 32, name: "Мидии", price: 60 },
  { id: 33, name: "Лимон", price: 10 },
];

export const pizzaData = [
  {
    id: 1,
    name: "Пепперони",
    price: 500,
    image: "pepperoni.svg",
    ingredients: [1, 2, 3, 4],
  },
  {
    id: 2,
    name: "Маргарита",
    price: 400,
    image: "margarita.svg",
    ingredients: [5, 6, 7, 8],
  },
  {
    id: 3,
    name: "Четыре сыра",
    price: 550,
    image: "four-cheese.svg",
    ingredients: [9, 10, 11, 12],
  },
  {
    id: 4,
    name: "Гавайская",
    price: 480,
    image: "hawaiian.svg",
    ingredients: [13, 14, 2, 1],
  },
  {
    id: 5,
    name: "Барбекю",
    price: 530,
    image: "barbecue.svg",
    ingredients: [15, 16, 17, 18],
  },
  {
    id: 6,
    name: "Вегетарианская",
    price: 450,
    image: "vegetarian.svg",
    ingredients: [19, 20, 21, 22],
  },
  {
    id: 7,
    name: "Мясная",
    price: 560,
    image: "meat.svg",
    ingredients: [23, 16, 15, 24],
  },
  {
    id: 8,
    name: "Дьябло",
    price: 520,
    image: "diablo.svg",
    ingredients: [25, 2, 4, 26],
  },
  {
    id: 9,
    name: "С грибами",
    price: 470,
    image: "mushrooms.svg",
    ingredients: [27, 28, 29, 17],
  },
  {
    id: 10,
    name: "С морепродуктами",
    price: 600,
    image: "seafood.svg",
    ingredients: [30, 31, 32, 33],
  },
];
